name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Aplicar migrations
        run: |
          python manage.py migrate

      - name: Verificar se o Django está ok
        run: |
          python manage.py check

      - name: Rodar testes
        run: |
          pytest
